version: '3.3'

services:
  mbapi:
    # image: epinux/fastapi:latest
    image: epinux/pdal-mbio:5.7.5
    build:
      context: ./docker
    environment:
      DEBUG: 1
      PYTHONUNBUFFERED: 1
      LOGLEVEL: DEBUG
      FORWARDED_ALLOW_IPS: "*"
    hostname: mbapi
    volumes:
      - ./apps/mbapp:/app
      - ./mbdata:/app/mbdata
    ports:
      - 90:80

  jupyter:
    # image: epinux/nvxviz-lab:test
    image: epinux/mbio_lab
    build:
      context: docker/jupyter
      dockerfile: dockerfile
    environment:
      - NB_DIR=/home/jovyan/notebooks
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./mbdata:/home/jovyan/notebooks/mbdata
      # - /media/epinux/media_ext1/MBES:/home/jovyan/notebooks/MBES
      - jupyter_mbio_lab_data:/home/jovyan/.jupyter/
      - jupyter_mbio_user_data:/home/jovyan/.local

    ports:
      - 8888:8888

volumes:
  jupyter_mbio_lab_data:
  jupyter_mbio_user_data:
